export const KERNING_CLASS_SCHEME_CHALENE = [

  { name: 'A1', side: 'verso', names: ['A', 'AE'] },
  { name: 'C1', side: 'verso', names: ['C', 'G'] },
  { name: 'B1', side: 'verso', names: ['S', 'B'] },
  { name: 'E1', side: 'verso', names: ['E', 'OE'] },
  { name: 'F1', side: 'verso', names: ['F'] },
  { name: 'H1', side: 'verso', names: ['H', 'M', 'N'] },
  { name: 'I1', side: 'verso', names: ['I'] },
  { name: 'L1', side: 'verso', names: ['L'] },
  { name: 'O1', side: 'verso', names: ['D', 'O'] },
  { name: 'P1', side: 'verso', names: ['P'] },
  { name: 'Q1', side: 'verso', names: ['Q'] },
  { name: 'R1', side: 'verso', names: ['R'] },
  { name: 'T1', side: 'verso', names: ['T'] },
  { name: 'U1', side: 'verso', names: ['U', 'J'] },
  { name: 'V1', side: 'verso', names: ['V', 'W', 'Y'] },
  { name: 'X1', side: 'verso', names: ['X', 'K', 'Z'] },

  { name: 'A2', side: 'recto', names: ['A', 'AE'] },
  { name: 'H2', side: 'recto', names: ['B', 'D', 'E', 'F', 'H', 'K', 'L', 'M', 'N', 'P', 'R'] },
  { name: 'I2', side: 'recto', names: ['I'] },
  { name: 'J2', side: 'recto', names: ['J'] },
  { name: 'L2', side: 'recto', names: ['L'] },
  { name: 'O2', side: 'recto', names: ['C', 'G', 'O', 'Q', 'OE'] },
  { name: 'T2', side: 'recto', names: ['T'] },
  { name: 'S2', side: 'recto', names: ['S'] },
  { name: 'V2', side: 'recto', names: ['V', 'W', 'Y'] },
  { name: 'X2', side: 'recto', names: ['X', 'Z'] },
]