export const KERNING_CLASS_SCHEME_CHALENE = [

  { '1st': true, name: 'A1', names: ['A', 'AE'] },
  { '1st': true, name: 'C1', names: ['C', 'G'] },
  { '1st': true, name: 'B1', names: ['S', 'B'] },
  { '1st': true, name: 'E1', names: ['E', 'OE'] },
  { '1st': true, name: 'F1', names: ['F'] },
  { '1st': true, name: 'H1', names: ['H', 'M', 'N'] },
  { '1st': true, name: 'I1', names: ['I'] },
  { '1st': true, name: 'L1', names: ['L'] },
  { '1st': true, name: 'O1', names: ['D', 'O'] },
  { '1st': true, name: 'P1', names: ['P'] },
  { '1st': true, name: 'Q1', names: ['Q'] },
  { '1st': true, name: 'R1', names: ['R'] },
  { '1st': true, name: 'T1', names: ['T'] },
  { '1st': true, name: 'U1', names: ['U', 'J'] },
  { '1st': true, name: 'V1', names: ['V', 'W', 'Y'] },
  { '1st': true, name: 'X1', names: ['X', 'K', 'Z'] },

  { '2nd': true, name: 'A2', names: ['A', 'AE'] },
  { '2nd': true, name: 'H2', names: ['B', 'D', 'E', 'F', 'H', 'K', 'L', 'M', 'N', 'P', 'R'] },
  { '2nd': true, name: 'I2', names: ['I'] },
  { '2nd': true, name: 'J2', names: ['J'] },
  { '2nd': true, name: 'L2', names: ['L'] },
  { '2nd': true, name: 'O2', names: ['C', 'G', 'O', 'Q', 'OE'] },
  { '2nd': true, name: 'T2', names: ['T'] },
  { '2nd': true, name: 'S2', names: ['S'] },
  { '2nd': true, name: 'V2', names: ['V', 'W', 'Y'] },
  { '2nd': true, name: 'X2', names: ['X', 'Z'] },

]