export const GROUP_SCHEME_UPPER = {
  A: ['A', 'Aacute', 'Abreve', 'Acircumflex', 'Adieresis', 'Agrave', 'Amacron', 'Aogonek', 'Aring', 'Atilde', 'Acircumflexgrave', 'Acircumflexhoi', 'Acircumflextilde', 'Acircumflexdotbelow', 'Abreveacute', 'Abrevegrave', 'Abrevehoi', 'Abrevetilde', 'Abrevedotbelow', 'Aringacute', 'Adblgrave', 'Ainvertedbreve', 'Adotbelow', 'Ahoi', 'Acircumflexacute', 'Ahookabove', 'Acircumflexhookabove', 'Abrevehookabove'],
  B: ['B'],
  C: ['C', 'Cacute', 'Ccaron', 'Ccedilla', 'Ccircumflex', 'Cdotaccent'],
  D: ['D', 'Dcaron', 'Dcroat', 'Dzcaron', 'Ddotbelow', 'Dlinebelow', 'DZcaron'],
  E: ['E', 'Eacute', 'Ebreve', 'Ecaron', 'Ecircumflex', 'Edieresis', 'Edotaccent', 'Egrave', 'Emacron', 'Eogonek', 'Edblgrave', 'Einvertedbreve', 'Emacrongrave', 'Emacronacute', 'Ecedillabreve', 'Edotbelow', 'Ehoi', 'Etilde', 'Ecircumflexacute', 'Ecircumflexgrave', 'Ecircumflexhoi', 'Ecircumflextilde', 'Ecircumflexdotbelow', 'Ehookabove', 'Ecircumflexhookabove'],
  F: ['F'],
  G: ['G', 'Gbreve', 'Gcircumflex', 'Gcommaaccent', 'Gdotaccent'],
  H: ['H', 'Hbar', 'Hcircumflex', 'Hdotbelow', 'Hbrevebelow'],
  I: ['I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis', 'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Itilde', 'Idblgrave', 'Iinvertedbreve', 'Idieresisacute', 'Ihoi', 'Idotbelow', 'Ihookabove'],
  J: ['J', 'Jcircumflex'],
  K: ['K', 'Kcommaaccent'],
  L: ['L', 'Lacute', 'Lcaron', 'Lcommaaccent', 'Ldot', 'Lslash', 'Ldotbelow', 'Llinebelow'],
  M: ['M', 'Mdotbelow'],
  N: ['N', 'Nacute', 'Ncaron', 'Ncommaaccent', 'Ntilde', 'Ndot', 'Ndotbelow', 'Nlinebelow'],
  O: ['O', 'Oacute', 'Obreve', 'Ocircumflex', 'Odieresis', 'Ograve', 'Omacron', 'Oslash', 'Otilde', 'Ohungarumlaut', 'Ohorn', 'Oslashacute', 'Omegatonos', 'Odotbelow', 'Ohookabove', 'Ocircumflexacute', 'Ocircumflexgrave', 'Ocircumflexhookabove', 'Ocircumflextilde', 'Ocircumflexdotbelow', 'Ohornacute', 'Ohorngrave', 'Ohornhookabove', 'Ohorntilde', 'Ohorndotbelow', 'Ohm'],
  P: ['P'],
  Q: ['Q'],
  R: ['R', 'Racute', 'Rcaron', 'Rcommaaccent', 'Rdblgrave', 'Rinvertedbreve', 'Rdotbelow', 'Rlinebelow'],
  S: ['S', 'Sacute', 'Scaron', 'Scedilla', 'Scircumflex', 'Scommaaccent'],
  T: ['T', 'Tbar', 'Tcaron', 'Tcommaaccent'],
  U: ['U', 'Uacute', 'Ubreve', 'Ucircumflex', 'Udieresis', 'Ugrave', 'Uhungarumlaut', 'Umacron', 'Uogonek', 'Uring', 'Utilde', 'Uhorn', 'Udotbelow', 'Uhookabove', 'Uhornacute', 'Uhorngrave', 'Uhornhookabove', 'Uhorntilde', 'Uhorndotbelow'],
  V: ['V'],
  W: ['W', 'Wcircumflex', 'Wgrave', 'Wacute', 'Wdieresis'],
  X: ['X'],
  Y: ['Y', 'Yacute', 'Ycircumflex', 'Ydieresis', 'Ygrave', 'Ydotbelow', 'Yhookabove', 'Ytilde'],
  Z: ['Z', 'Zacute', 'Zdotaccent', 'Zcaron'],
  AE: ['AE', 'AEacute'],
  OE: ['OE'],
  NJ: ['NJ'],
  LJ: ['LJ'],
  Nj: ['Nj'],
  Lj: ['Lj'],
  IJ: ['IJ'],
  Eth: ['Eth'],
  Eng: ['Eng'],
  Thorn: ['Thorn'],
  germandbls: ['germandbls'],
  Alpha: ['Alphatonos', 'Alpha'],
  Beta: ['Beta'],
  Gamma: ['Gamma'],
  Delta: ['Delta'],
  Epsilon: ['Epsilontonos', 'Epsilon'],
  Zeta: ['Zeta'],
  Eta: ['Etatonos', 'Eta'],
  Theta: ['Theta'],
  Iota: ['Iotatonos', 'Iota', 'Iotadieresis'],
  Kappa: ['Kappa'],
  Lambda: ['Lambda'],
  Mu: ['Mu'],
  Nu: ['Nu'],
  Xi: ['Xi'],
  Omicron: ['Omicrontonos', 'Omicron'],
  Pi: ['Pi'],
  Rho: ['Rho'],
  Sigma: ['Sigma'],
  Tau: ['Tau'],
  Upsilon: ['Upsilontonos', 'Upsilon', 'Upsilondieresis'],
  Phi: ['Phi'],
  Chi: ['Chi'],
  Psi: ['Psi'],
}