export const GROUP_SCHEME_LOWER = {
  a: ['a', 'aacute', 'abreve', 'acircumflex', 'adieresis', 'agrave', 'amacron', 'aogonek', 'aring', 'atilde', 'acircumflexgrave', 'acircumflexhoi', 'acircumflextilde', 'acircumflexdotbelow', 'abreveacute', 'abrevegrave', 'abrevehoi', 'abrevetilde', 'abrevedotbelow', 'aringacute', 'adblgrave', 'ainvertedbreve', 'adotbelow', 'ahoi', 'acircumflexacute', 'ahookabove', 'acircumflexhookabove', 'abrevehookabove'],
  b: ['b'],
  c: ['c', 'cacute', 'ccaron', 'ccedilla', 'ccircumflex', 'cdotaccent', 'cent'],
  d: ['d', 'dcaron', 'dcroat', 'dzcaron', 'ddotbelow', 'dlinebelow', 'dzcaron'],
  e: ['e', 'eacute', 'ebreve', 'ecaron', 'ecircumflex', 'edieresis', 'edotaccent', 'egrave', 'emacron', 'eogonek', 'edblgrave', 'einvertedbreve', 'emacrongrave', 'emacronacute', 'ecedillabreve', 'edotbelow', 'ehoi', 'etilde', 'ecircumflexacute', 'ecircumflexgrave', 'ecircumflexhoi', 'ecircumflextilde', 'ecircumflexdotbelow', 'ehookabove', 'ecircumflexhookabove'],
  f: ['f'],
  g: ['g', 'gbreve', 'gcircumflex', 'gcommaaccent', 'gdotaccent'],
  h: ['h', 'hbar', 'hcircumflex', 'hdotbelow', 'hbrevebelow'],
  i: ['i', 'iacute', 'ibreve', 'icircumflex', 'idieresis', 'idotaccent', 'igrave', 'imacron', 'iogonek', 'itilde', 'idblgrave', 'iinvertedbreve', 'idieresisacute', 'ihoi', 'idotbelow', 'ihookabove', 'dotlessi'],
  j: ['j', 'jcircumflex'],
  k: ['k', 'kcommaaccent'],
  l: ['l', 'lacute', 'lcaron', 'lcommaaccent', 'ldot', 'lslash', 'ldotbelow', 'llinebelow'],
  m: ['m', 'mdotbelow'],
  n: ['n', 'nacute', 'ncaron', 'ncommaaccent', 'ntilde', 'ndot', 'ndotbelow', 'nlinebelow'],
  o: ['o', 'oacute', 'obreve', 'ocircumflex', 'odieresis', 'ograve', 'omacron', 'oslash', 'otilde', 'ohungarumlaut', 'ohorn', 'oslashacute', 'omegatonos', 'odotbelow', 'ohookabove', 'ocircumflexacute', 'ocircumflexgrave', 'ocircumflexhookabove', 'ocircumflextilde', 'ocircumflexdotbelow', 'ohornacute', 'ohorngrave', 'ohornhookabove', 'ohorntilde', 'ohorndotbelow', 'ohm'],
  p: ['p'],
  q: ['q'],
  r: ['r', 'racute', 'rcaron', 'rcommaaccent', 'rdblgrave', 'rinvertedbreve', 'rdotbelow', 'rlinebelow'],
  s: ['s', 'sacute', 'scaron', 'scedilla', 'scircumflex', 'scommaaccent'],
  t: ['t', 'tbar', 'tcaron', 'tcommaaccent'],
  u: ['u', 'uacute', 'ubreve', 'ucircumflex', 'udieresis', 'ugrave', 'uhungarumlaut', 'umacron', 'uogonek', 'uring', 'utilde', 'uhorn', 'udotbelow', 'uhookabove', 'uhornacute', 'uhorngrave', 'uhornhookabove', 'uhorntilde', 'uhorndotbelow'],
  v: ['v'],
  w: ['w', 'wcircumflex', 'wgrave', 'wacute', 'wdieresis'],
  x: ['x'],
  y: ['y', 'yacute', 'ycircumflex', 'ydieresis', 'ygrave', 'ydotbelow', 'yhookabove', 'ytilde'],
  z: ['z', 'zacute', 'zdotaccent', 'zcaron'],
  germandbls: ['germandbls'],
  ae: ['ae', 'aeacute'],
  oe: ['oe'],
  nj: ['nj'],
  lj: ['lj'],
  ij: ['ij'],
  eth: ['eth'],
  eng: ['eng'],
  thorn: ['thorn'],
  alpha: ['alphatonos', 'alpha'],
  beta: ['beta'],
  gamma: ['gamma'],
  delta: ['delta'],
  epsilon: ['epsilontonos', 'epsilon'],
  zeta: ['zeta'],
  eta: ['etatonos', 'eta'],
  theta: ['theta'],
  iota: ['iotatonos', 'iota', 'iotadieresis'],
  kappa: ['kappa'],
  lambda: ['lambda'],
  mu: ['mu'],
  nu: ['nu'],
  xi: ['xi'],
  omicron: ['omicrontonos', 'omicron'],
  pi: ['pi'],
  rho: ['rho'],
  sigma: ['sigma'],
  tau: ['tau'],
  upsilon: ['upsilontonos', 'upsilon', 'upsilondieresis'],
  phi: ['phi'],
  chi: ['chi'],
  psi: ['psi'],
}