export const GROUPS_CHALENE = [

  { '1st': true, name: 'A1', names: ['A', 'AE'] },
  { '1st': true, name: 'C1', names: ['C', 'G'] },
  { '1st': true, name: 'B1', names: ['S', 'B', 'germandbls'] },
  { '1st': true, name: 'E1', names: ['E', 'OE'] },
  { '1st': true, name: 'F1', names: ['F'] },
  { '1st': true, name: 'H1', names: ['H', 'M', 'N', 'Eng'] },
  { '1st': true, name: 'I1', names: ['I'] },
  { '1st': true, name: 'L1', names: ['L'] },
  { '1st': true, name: 'O1', names: ['D', 'O', 'Eth'] },
  { '1st': true, name: 'P1', names: ['P'] },
  { '1st': true, name: 'Q1', names: ['Q'] },
  { '1st': true, name: 'R1', names: ['R'] },
  { '1st': true, name: 'T1', names: ['T'] },
  { '1st': true, name: 'U1', names: ['U', 'J', 'NJ', 'IJ', 'LJ'] },
  { '1st': true, name: 'V1', names: ['V', 'W', 'Y'] },
  { '1st': true, name: 'X1', names: ['X', 'K', 'Z'] },

  { '2nd': true, name: 'A2', names: ['A', 'AE'] },
  { '2nd': true, name: 'H2', names: ['B', 'D', 'E', 'F', 'H', 'K', 'L', 'M', 'N', 'P', 'R', 'Eng', 'NJ', 'LJ'] },
  { '2nd': true, name: 'I2', names: ['I', 'IJ'] },
  { '2nd': true, name: 'J2', names: ['J'] },
  { '2nd': true, name: 'L2', names: ['L'] },
  { '2nd': true, name: 'O2', names: ['C', 'G', 'O', 'Q', 'OE'] },
  { '2nd': true, name: 'T2', names: ['T'] },
  { '2nd': true, name: 'S2', names: ['S'] },
  { '2nd': true, name: 'U2', names: ['U'] },
  { '2nd': true, name: 'V2', names: ['V', 'W', 'Y'] },
  { '2nd': true, name: 'X2', names: ['X', 'Z'] },

  { '1st': true, name: 'n1', names: ['a', 'b', 'm', 'n', 'h'] },
  { '1st': true, name: 'o1', names: ['b', 'e', 'o', 'p', 'ae', 'oe', 'eth'] },
  { '1st': true, name: 'c1', names: ['c'] },
  { '1st': true, name: 'l1', names: ['d', 'l'] },
  { '1st': true, name: 'f1', names: ['f'] },
  { '1st': true, name: 'j1', names: ['g', 'j', 'q', 'ij', 'nj', 'lj'] },
  { '1st': true, name: 'x1', names: ['k', 'x', 'z'] },
  { '1st': true, name: 'r1', names: ['r'] },
  { '1st': true, name: 's1', names: ['s'] },
  { '1st': true, name: 't1', names: ['t'] },
  { '1st': true, name: 'i1', names: ['i', 'u'] },
  { '1st': true, name: 'v1', names: ['v', 'w', 'y'] },

  { '2nd': true, name: 'n2', names: ['m', 'n', 'r', 'nj'] },
  { '2nd': true, name: 'o2', names: ['c', 'd', 'e', 'g', 'o', 'oe', 'q', 'cent', 'eth'] },
  { '2nd': true, name: 'l2', names: ['b', 'h', 'k', 'l', 'p', 'lj', 'thorn'] },
  { '2nd': true, name: 'f2', names: ['f', 'germandbls', 'Eth'] },
  { '2nd': true, name: 'x2', names: ['x', 'z'] },
  { '2nd': true, name: 's2', names: ['s'] },
  { '2nd': true, name: 't2', names: ['t', 'u'] },
  { '2nd': true, name: 'i2', names: ['i', 'ij', 'eng'] },
  { '2nd': true, name: 'v2', names: ['v', 'w', 'y'] },
  { '2nd': true, name: 'a2', names: ['a', 'ae'] },
  { '2nd': true, name: 'p2', names: ['p'] }, // miu

]